version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///./app/test.db
  db:
    image: "sqlite:latest"
    volumes:
      - ./app/test.db:/app/test.db
