version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=${SECRET_KEY}
